### ISSUE TITLE
オンライン対戦提出（アリクイさんチーム）

### ISSUE THREAD

**Issue by katsube** [katsube/neec2017B#33]
GItHubのリポジトリのURLを投稿してください。

* 途中で変更した場合は再度投稿をお願いします。
* 2月5日時点の状態を評価対象とします。
* 2月5日中に投稿がない場合はチーム全員の評価が付きませんので注意してください。

**Comment by MizukiHayashi** [comment]
https://github.com/Syuvi/ArikuiTeam.git

**Comment by katsube** [comment]
以下の内容を2月5日の授業終了までに投稿してください。
（リポジトリのURLが変更になった場合はそちらも合わせて記入をお願いします）

1. 最終的なゲームタイトル
2. ゲーム概要
    * 特徴やルール
    * 他チームとの差別化ポイント
    * 特にがんばった点

**Comment by MizukiHayashi** [comment]
タイトル：ハングリージャンケン
特徴・ルール：２人でじゃんけんを行い、勝った方がスイーツを食べる。
　　　　　　　満腹度がMAXになったほうが勝ち。
　　　　　　　勝った手によって食べれられる個数が変化する
　　　　　　　グー１個　チョキ２個　パー５個
差別化のポイント：　勝った手によって食べられる個数が変わるので心理戦のような感じになる点
特に頑張った点：　ライブラリを使わないで作ってる点
