### ISSUE TITLE
オンライン対戦提出（あんこうチーム）

### ISSUE THREAD

**Issue by katsube** [katsube/neec2017B#34]
GItHubのリポジトリのURLを投稿してください。

* 途中で変更した場合は再度投稿をお願いします。
* 2月5日時点の状態を評価対象とします。
* 2月5日中に投稿がない場合はチーム全員の評価が付きませんので注意してください。

**Comment by JAPseed** [comment]
https://github.com/JAPseed/phpteamgame.git

**Comment by katsube** [comment]
以下の内容を2月5日の授業終了までに投稿してください。
（リポジトリのURLが変更になった場合はそちらも合わせて記入をお願いします）

1. 最終的なゲームタイトル
2. ゲーム概要
    * 特徴やルール
    * 他チームとの差別化ポイント
    * 特にがんばった点

**Comment by JAPseed** [comment]
ゲームタイトル:チョコスロ
ゲーム概要
・ルール:スロットで得点を稼いで、スコアが高い方が勝ち
・差別化:スコア制なところ
・がんばった点:2ユーザーのマッチング部分
