### ISSUE TITLE
オンライン対戦提出（カメさんチーム）

### ISSUE THREAD

**Issue by katsube** [katsube/neec2017B#36]
GItHubのリポジトリのURLを投稿してください。

* 途中で変更した場合は再度投稿をお願いします。
* 2月5日時点の状態を評価対象とします。
* 2月5日中に投稿がない場合はチーム全員の評価が付きませんので注意してください。

**Comment by KousukeNakagawa** [comment]
https://github.com/KousukeNakagawa/-MondayTeam.git

**Comment by katsube** [comment]
以下の内容を2月5日の授業終了までに投稿してください。
（リポジトリのURLが変更になった場合はそちらも合わせて記入をお願いします）

1. 最終的なゲームタイトル
2. ゲーム概要
    * 特徴やルール
    * 他チームとの差別化ポイント
    * 特にがんばった点

**Comment by KousukeNakagawa** [comment]
1,スイーツタワーバトル
2,ルール：制限時間内に交代でランダムに選ばれるスイーツを落としていき、最後に多く残っていたプレイヤーの勝利
  他チームとの差別化ポイント：如何に相手のスイーツを落とさせ自分のスイーツを保てておくか
  特にがんばった点：班員なかよく
