### ISSUE TITLE
オンライン対戦提出（サメさんチーム） ※

### ISSUE THREAD

**Issue by katsube** [katsube/neec2017B#38]
GItHubのリポジトリのURLを投稿してください。

* 途中で変更した場合は再度投稿をお願いします。
* 2月5日時点の状態を評価対象とします。
* 2月5日中に投稿がない場合はチーム全員の評価が付きませんので注意してください。

**Comment by katsube** [comment]
以下の内容を2月5日の授業終了までに投稿してください。
（リポジトリのURLが変更になった場合はそちらも合わせて記入をお願いします）

1. 最終的なゲームタイトル
2. ゲーム概要
    * 特徴やルール
    * 他チームとの差別化ポイント
    * 特にがんばった点

**Comment by katsube** [comment]
リポジトリのURLも必ず提出してね。

**Comment by koutarou-Azami** [comment]
https://github.com/koutarou-Azami/Sweets

**Comment by koutarou-Azami** [comment]
タイトル：3分スイーツ
ゲーム概要
・ルール
素材ガチャから素材カードを5枚取得し、素材の組み合わせで作られた役に応じたスイーツが作られる。
役の合計取得点が高い方のプレイヤーが勝利する。
ガチャから取得した素材カードは一度引いたら交換するなどのことはできず、最初にひいた眼で勝敗が決まる。
役がそろわなかった場合は0点となり、点数を取得することができない。
お互いが0点だった場合は引き分けになる。
・他チームとの差別点
ガチャに作成要素を加えてシミュレート要素を与えました。
・特に頑張った点
リポジトリの作成とGitHubとの連携
ルールの決定
対戦する相手のデータのやり取り
