### ISSUE TITLE
オンライン対戦提出（たんぽぽチーム）

### ISSUE THREAD

**Issue by katsube** [katsube/neec2017B#39]
GItHubのリポジトリのURLを投稿してください。

* 途中で変更した場合は再度投稿をお願いします。
* 2月5日時点の状態を評価対象とします。
* 2月5日中に投稿がない場合はチーム全員の評価が付きませんので注意してください。

**Comment by TYasutake** [comment]
https://github.com/TYasutake/tanpopo

リポジトリのURL

**Comment by katsube** [comment]
以下の内容を2月5日の授業終了までに投稿してください。
（リポジトリのURLが変更になった場合はそちらも合わせて記入をお願いします）

1. 最終的なゲームタイトル
2. ゲーム概要
    * 特徴やルール
    * 他チームとの差別化ポイント
    * 特にがんばった点

**Comment by TYasutake** [comment]
1.　＿＿＿＿＿＿
 　｜新コーナー｜
  　 ￣￣￣￣￣￣　チョコネミミッミ
2.ゲーム概要
〇特徴やルール
・サーバー側が出題した食べ物をクライアント側が判断していくゲーム。
　出題されたものがスイーツであれば「おいしー」、スイーツでなければ「いらなーい」、
　一度出題されたスイーツは「もうたべた」のボタンを選択していく。
　サーバー側が最初に20回分の食べ物を選択して、問題を作る。
　その後、クライアント側が回答していき、一度でもクライアント側が間違えなければクライアント側の勝利。間違えた場合サーバー側の勝利。
〇他チームとの差別化ポイント
・判断力だけではなく、記憶力も求められるようにしました。
〇特に頑張った点
・みんななかよく
