### ISSUE TITLE
オンライン対戦提出（レオポンさんチーム）

### ISSUE THREAD

**Issue by katsube** [katsube/neec2017B#40]
GItHubのリポジトリのURLを投稿してください。

* 途中で変更した場合は再度投稿をお願いします。
* 2月5日時点の状態を評価対象とします。
* 2月5日中に投稿がない場合はチーム全員の評価が付きませんので注意してください。

**Comment by rekoha058wa** [comment]
https://github.com/rekoha058wa/sosogu

**Comment by katsube** [comment]
以下の内容を2月5日の授業終了までに投稿してください。
（リポジトリのURLが変更になった場合はそちらも合わせて記入をお願いします）

1. 最終的なゲームタイトル
2. ゲーム概要
    * 特徴やルール
    * 他チームとの差別化ポイント
    * 特にがんばった点

**Comment by rekoha058wa** [comment]
タイトル：思考でSOSOGU!チョコレート

ルール、概要：先行、後行に分かれ、先行が選んだ数字を後行が当てるゲーム
　　　　　　　先行と後行の振り分けはスタート時はランダム、そのあとは交互に行われる
　　　　　　　結果によってチョコレートが注がれ、タンクに限界まで注がれた方が負け
　　　　　　　数字は１～９の中から選ぶ
　　　　先行：数字を当てられた場合、自分にチョコレートを注がれる
　　　　　　　逆に、数字を当てられなかった場合、相手にチョコレートを注ぐ
　　　　後行：数字を当てた場合、相手にチョコレートを注ぎ、
　　　　　　　当てられなかった場合、自分に注がれる

他のチームの差別化：ゲーム画面だけでなくリアルでの相手との思考バトルを行う点

頑張った点：サーバー周り（できているとは言っていない）
